### ISSUE TITLE
Should LanguageManger.shared.defaultLanguage work for non Storyboard/Nib apps?

### ISSUE THREAD

**Issue by eldarhealthyio** [Abedalkareem/LanguageManager-iOS#10]
`LanguageManger.shared.defaultLanguage = .nl` does seem to work, until I reset the app.

**Comment by Abedalkareem** [comment]
Hi eldarhealthyio,

Sorry for the delay, yes it's work for the both. (I just push new code that support the Storyboard)

Put this line in the app delegate.
`LanguageManger.shared.defaultLanguage = .nl`

if you want to change the app language again you need to use this method
`LanguageManager.shared.setLanguage(language: .en)`

Thank you!

**Comment by muni510** [comment]
Hi Abedalkareem,

Thanks for a very useful library. 
I have added the code as per instruction in my project, but storyboard translations not updating...

kindly help for it.
