### ISSUE TITLE
Non supported languages

### ISSUE THREAD

**Issue by DinoStarcic** [Abedalkareem/LanguageManager-iOS#15]
Hi im trying to use this with Slovenian language which is it the section of "other" your enum does not have the .sl lang. How can i bypass this to make it work? :)

**Comment by Abedalkareem** [comment]
Hi,

Thank you for reporting! 
This issue fixed on 1.1.0 version, please update the pods and if the issue is still there please reply here.

Thank you.

**Comment by DinoStarcic** [comment]
Hi :) Now it compiled the project but it dosent read from the .sl strings file, it works normally with .en

**Comment by DinoStarcic** [comment]
:) this seems to change it when i re run the app :D  

LanguageManager.shared.defaultLanguage = .de

LanguageManager.shared.setLanguage(language: .sl)
