### ISSUE TITLE
Image rotation is not working, not even included in the library; swift 5 upgrade is needed

### ISSUE THREAD

**Issue by Abanoub-Emil** [Abedalkareem/LanguageManager-iOS#19]
I found that the pod file does not contain the same code compared with the one in the example

**Comment by Abedalkareem** [comment]
Hi Abanoub,

Do you use CocoaPods or Carthage?

**Comment by Abanoub-Emil** [comment]
Cocopods
Actually, I removed the pod and used the .swift file in order to solve this issue

**Comment by Abedalkareem** [comment]
I just checked it with a new project and it's working fine, maybe you need to update the pods, 
I'll close the issue now and if you faced it again please reopen the issue. thank you.
