### ISSUE TITLE
Bundle Swizzling

### ISSUE THREAD

**Issue by samynu** [Abedalkareem/LanguageManager-iOS#20]
Was swizzling removed because apple does not allow on the app store?

**Comment by Abedalkareem** [comment]
Hi Samynu,
No, I removed it because it will affect the app if anyone is using services like [localise.io](https://lokalise.co/).
I think it will not affect anything you are doing, did you face any problem?

**Comment by samynu** [comment]
I observed that only upon calling setLanguage twice changes the NavigationBar title, and when I reopen the app NavigationBar goes back to the base language while all others remain fine.

**Comment by Abedalkareem** [comment]
You can localize the titles using title property inside the view controller by now.
`self.title = "controller title".localiz()`
I'm sorry for the trouble I caused for you doing this change, but the bundle swizzling was effecting the  localise.io service, also you can get the old code by looking at the previous releases.

Thank you.
