### ISSUE TITLE
Unable to set default language

### ISSUE THREAD

**Issue by laith-abdo** [Abedalkareem/LanguageManager-iOS#21]
thank you very much for this great job and awesome library
i tried it on many project and it worked perfectly , but i have old project that contains 2 storyboards ar and en , app stay crashed and it tell me about fatal error " default langue not set yet" can you advise please

**Comment by laith-abdo** [comment]
did you think because i use base Storyboard not english ??

**Comment by Abedalkareem** [comment]
Hi Laith,
Maybe you are doing something before setting the default language, try to put it in the first line inside `application: UIApplication, didFinishLaunchingWithOptions launchOptions`.

**Comment by AhmedBarghash** [comment]
@Abedalkareem 
do you mean this function 

   

>  func applicationDidFinishLaunching(_ application: UIApplication) {
>         <#code#>
>     }

**Comment by laith-abdo** [comment]
Thank you abdelkareem my issue solved , i will close this issue 
thank you for great job
