### ISSUE TITLE
Close app reopen 

### ISSUE THREAD

**Issue by MSawalha** [Abedalkareem/LanguageManager-iOS#22]
works like a charm with first run, but when i close the application and reopen it doesn't work at all only change the semantics in weird order and no english/arabic localization change it only change the semantics ...

**Comment by Abedalkareem** [comment]
Hi Mohammed, 
Did you follow the usage instructions? 
and remember that always you need to keep the following line in the first line of the app delegate

```
  func application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?) -> Bool {

    // Set the default language for the app
    LanguageManager.shared.defaultLanguage = .deviceLanguage

    return true
  }

```

**Comment by Abedalkareem** [comment]
Please if you still face the issue reopen it.

Thank you.
