### ISSUE TITLE
Trying to force content mode LTR , RTL in stackview regarding the change of language

### ISSUE THREAD

**Issue by MSawalha** [Abedalkareem/LanguageManager-iOS#23]
I am trying to force content mode in the stackviews regarding the change of language between eng and arabic, however i am expecting when i force mode, it shouldn't flip when i change the language, is there something missing or i am doing something wrong ?

**Comment by Abedalkareem** [comment]
Hi Mohammed,

if you need to do that, you need to do it from the code
`  @IBOutlet weak var stackView: UIStackView!`

```
  override func viewDidLoad() {
    super.viewDidLoad()
   stackView.semanticContentAttribute = .forceLeftToRight
  }
```
Thanks.

**Comment by MSawalha** [comment]
Thanks, will test it and close the issue when done, thanks for the fast response Cheers
