### ISSUE TITLE
UIBarButtonItem image not rotated.

### ISSUE THREAD

**Issue by rameezibrahim** [Abedalkareem/LanguageManager-iOS#25]
I have created the UIBarButtonItem programmatically as follows:

`UIBarButtonItem(image: UIImage(named: backButtonIconName), style: .plain, target: self, action: #selector(leftBarButtonAction(_ :)))`

How can I rotate the back button for RTL?]

Current screenshot:
<img width="786" alt="Screen Shot 2019-10-01 at 9 52 25 AM" src="https://user-images.githubusercontent.com/54498789/65937814-0f6fe580-e432-11e9-88f7-990c3283c03d.png">

**Comment by Abedalkareem** [comment]
Hi,
What you can do is this:
```
let backButtonIconName = LanguageManager.shared.isRightToLeft ? "right_arrow" : "left_image"
UIBarButtonItem(image: UIImage(named: backButtonIconName), style: .plain, target: self, action: #selector(leftBarButtonAction(_ :)))
```
Thank you.
