### ISSUE TITLE
navigation buttons not localized and natural text alignment in placeholder not working correctly as expected

### ISSUE THREAD

**Issue by mahmoudOmara** [Abedalkareem/LanguageManager-iOS#26]
<img width="371" alt="Screen Shot 2019-10-01 at 12 02 49 PM" src="https://user-images.githubusercontent.com/42321936/65953258-de98ac00-e443-11e9-8f0f-ef6d97824ba1.png">

**Comment by Abedalkareem** [comment]
Hi,
The text field alignment is depending on the language you are writing with.
Please check here: https://github.com/Abedalkareem/LanguageManager-iOS/issues/12.

Thank you.
