### ISSUE TITLE
Localizable strings won't work as expected

### ISSUE THREAD

**Issue by AbdulsalamMansour** [Abedalkareem/LanguageManager-iOS#27]
when I use the following string extension 
    var localized: String {
        return NSLocalizedString(self, tableName: nil, bundle: Bundle.main, value: "", comment: "")
    }

I won't get the Arabic string even after I set the app language to Arabic using the library

is there a way to use the library and still get the correct value from Localizable.strings

**Comment by Abedalkareem** [comment]
Use the library ```localiz``` function.

```
public extension String {

  ///
  /// Localize the current string to the selected language
  ///
  /// - returns: The localized string
  ///
  func localiz(comment: String = "") -> String {
    guard let bundle = Bundle.main.path(forResource: LanguageManager.shared.currentLanguage.rawValue, ofType: "lproj") else {
      return NSLocalizedString(self, comment: comment)
    }

    let langBundle = Bundle(path: bundle)
    return NSLocalizedString(self, tableName: nil, bundle: langBundle!, comment: comment)
  }

}
```

if you still want to use your extension you can do this:
```
var localized: String {
  return self. localiz()
}
```

Thank you.
