### ISSUE TITLE
Language not changed iOS 13 if the system language is English

### ISSUE THREAD

**Issue by anandabayu** [Abedalkareem/LanguageManager-iOS#28]
Hey, I used swift 5 and iOS 13 and my language not changed after I clicked the button.

It's changed after I go to a different root view and go back.

I found it in LanguageManager.swift file that you used AppDelegate, iOS 13 use ScenceDelegate instead I think, can you help to change the language instantly in iOS 13?

**Comment by anandabayu** [comment]
I've solved this with set the Language first, then set rootViewController manually

LanguageManager.shared.setLanguage(language: .id)
// then set rootViewController manual here

But, the other problem appears, the language wouldn't change if the system language is not the language I want (in this case Indonesia). If my phone language is English then the app language wouldn't change, but if I change the phone language to Indonesia then the app language can change.

I hope any solution for this.

**Comment by anandabayu** [comment]
I found the problem was with the (lang).lproj folder itself, for Indonesia the folder become "id-ID.lproj".

but the return value of LanguageManager.shared.currentLanguage.rawValue is just "id"

so, I edit your extension function "localiz": 

`func localiz(comment: String = "") -> String {
    
    let lang = LanguageManager.shared.currentLanguage.rawValue
    
    var newLang = "en"
    
    if lang == "id" {
        newLang = "id-ID"
    }
    
    guard let bundle = Bundle.main.path(forResource: newLang, ofType: "lproj") else {
      return NSLocalizedString(self, comment: comment)
    }

    let langBundle = Bundle(path: bundle)
    
    return NSLocalizedString(self, tableName: nil, bundle: langBundle!, comment: comment)
  }`

and the problem is gone, I think you should add this for a future update for other languages too, and thanks for the library. 😁

**Comment by Abedalkareem** [comment]
Hi anandabyu,

Yes for sure I'll add this on the next release.

Thank you!
