### ISSUE TITLE
UITextfield Placeholder alignment won't change iOS13

### ISSUE THREAD

**Issue by Abdulaziz-si** [Abedalkareem/LanguageManager-iOS#29]
Hi
I'm building an app with iOS13 SDK when I change the language to Arabic the UITextfield placeholder stay on the left side I made sure that the UITextfield alignment is natural,
so what should I do any suggestions ?
and one more thing that when I type in Arabic the text alignment is right, when typing in English the alignment is left, should it be depending on the app language ?

**Comment by Abedalkareem** [comment]
Hi Abdulaziz, 
The text field alignment is depending on the language you are writing with.
Please check here: https://github.com/Abedalkareem/LanguageManager-iOS/issues/12
