### ISSUE TITLE
Changing language only works after restarting app

### ISSUE THREAD

**Issue by SonicGerkor** [Abedalkareem/LanguageManager-iOS#36]
Hi, I tried the library and the language is set properly, but only after restarting the app, do you have a solution for this?
The bundle doesn't seem to be updating correctly or something like that.

Thanks.

**Comment by Abedalkareem** [comment]
Hi,

Can you please download the example and try if it is working fine at your side? if yes please compare the two of them and try to follow the example.

Thank you.

**Comment by Abedalkareem** [comment]
Please if this issue is still there reopen the issue with more information.
Thank you.
