### ISSUE TITLE
setLanguage for version 1.2.0 not working on simulator.

### ISSUE THREAD

**Issue by rohankanoo** [Abedalkareem/LanguageManager-iOS#37]
setLanguage function prior to this release, used to work on both simulator and real device. After updating to versin 1.2.0 it has stopped working on simulator, although it's working fine on a real device.

**Comment by Abedalkareem** [comment]
Hi,
What is the language of the simulator? is it an iPhone or an iPad? what is the os number and is the project using SceneDelegate?

Thank you.

**Comment by Abedalkareem** [comment]
Please if the issue is still there reopen the issue with more information as I tried and everything working fine.
