### ISSUE TITLE
Localize info.plist privacy messages 

### ISSUE THREAD

**Issue by Abdulaziz-si** [Abedalkareem/LanguageManager-iOS#38]
Hello
thank you for the amazing SDK
I'm wondering how can I localize info.plist privacy messages
such as "Privacy - Location When In Use Usage Description" or maybe "Privacy - Camera Usage Description"
I tried to use keywords from localizable.string  file but nothing happened , so is there a different  way to do it or I'm missing something ?

**Comment by Abedalkareem** [comment]
Hi Abdulaziz.
You can follow this tutorial 
https://medium.com/@guerrix/info-plist-localization-ad5daaea732a

Please let me know if this fixes the issue.

Thank you!

**Comment by Abdulaziz-si** [comment]
Unfortunately that doesn't worked, still same issue

**Comment by Abdulaziz-si** [comment]
My bad , I totally misunderstood this section from the tutorial "Just add the key(which needs to be the same as is in the Info.plist )" 
I was following the same concept in the localizable.string like so: 
in InfoPlist.strings:
"enableLocationDescription" = "in order to show and deliver available products near you, we need to access your location";
then in info.plist:
Privacy - Location When In Use Usage Description = enableLocationDescription
this is wrong...❌

✅The correct way to do it is:
in InfoPlist.strings:
"NSLocationWhenInUseUsageDescription" = "in order to show and deliver available products near you, we need to access your location";
and in the info.plist feel free to write any thing you want because the value well be token from the InfoPlist.strings
for me I used the same value from the English description , so if for some reasons InfoPlist.strings was ignored the user will see the description in English instead of empty or gibberish description

⚠️ The key "NSLocationWhenInUseUsageDescription" can be seen when you open the info.plist as source code like in the picture
<img width="1352" alt="Screen Shot 2020-02-15 at 04 50 08" src="https://user-images.githubusercontent.com/51816122/74579882-37aa4c00-4faf-11ea-8f0d-a4ec23e96e3d.png">
