### ISSUE TITLE
Does this work with SwiftUI?

### ISSUE THREAD

**Issue by sailorpatrick** [Abedalkareem/LanguageManager-iOS#42]

**Comment by carlosrc** [comment]
I'm also interested.
Any progress? 
Thanks.

**Comment by aligutierrez** [comment]
Has anybody tried with SwiftUI

**Comment by Abedalkareem** [comment]
Hi guys,
I'm working on something for SwiftUI, I hope i will be able to finish it soon. I'll update you once I finish.

Thank you.

**Comment by saadelm** [comment]
me too I'm interested about it

**Comment by delvinwidjaja** [comment]
Hi, is there any update for SwiftUI?

**Comment by Abedalkareem** [comment]
Hi guys,
I released a SwiftUI language manager,

https://github.com/Abedalkareem/LanguageManager-SwiftUI

@delvinwidjaja @saadelm @aligutierrez  @carlosrc @sailorpatrick 

Thank you for your support!!
