### ISSUE TITLE
Very rubbish Library.

### ISSUE THREAD

**Issue by Rjmaurya13** [Abedalkareem/LanguageManager-iOS#44]
After adding this library my project become a mess. 
Getting unnecessary crash many times. 

"Fatal error: Did you set the default language for the app?"

I don't recommend to use this lib.

**Comment by Abedalkareem** [comment]
The solution:
```
LanguageManager.shared.defaultLanguage = .deviceLanguage
```

The library could be not that good, could have some problems but I'm using this in apps with +1m downloads and it's working fine. However, I don't have any problem giving your opinion and what do you think about it. but you need to have some respect and pick the correct words to describe what do you want as that represents you as a "Senior iOS developer". 

Thank you, and I hope that you will help to make it good.

**Comment by sam961** [comment]
@Rjmaurya13 
First of all ,
the library is working fine and you have to thank @Abedalkareem  for the hard work.
If you have any issue, you can open a case to discuss it.
as he said the solution is to add
`LanguageManager.shared.defaultLanguage = .deviceLanguage`

**Comment by Rjmaurya13** [comment]
Do you know why I used this words? If I was using this lib mins I have followed all integration steps. 
I know below is the first step `LanguageManager.shared.defaultLanguage = .deviceLanguage`.

Then later found random crash stating below error "Fatal error: Did you set the default language for the app?".

As a senior iOS developer, I understand and have used manu library and done many project. Now I am using my own solution for Language. That solution can be a lib, but I don't care about library and don't have time to make lib for small solution.

I apologies for the bad word, I am removing now.
