### ISSUE TITLE
iOS  language change in front page is not working

### ISSUE THREAD

**Issue by premkumarsepuri** [Abedalkareem/LanguageManager-iOS#45]
im trying to change language in front page but front page ui is getting freezes

**Comment by premkumarsepuri** [comment]
BSMachError: port 7803; (os/kern) invalid capability (0x14) "Unable to insert COPY_SEND" getting this error. thank you

**Comment by Abedalkareem** [comment]
Hi,
Did you check this?
https://stackoverflow.com/questions/39676762/error-bsmacherror-port-1607-os-kern-invalid-capability-0x14-unable-to-i
