### ISSUE TITLE
Textfield RTL

### ISSUE THREAD

**Issue by sam961** [Abedalkareem/LanguageManager-iOS#47]
Hi Abedalkareem,
First thank your for this amazing library.
The issue I face is on text field alignment...
i made the alignment natural , but still the text reading  from Left to right.
Also i tested this on your demo project and same result.
What could be this issue ?

**Comment by Abedalkareem** [comment]
Hi Sam!
can you please check this?
https://github.com/Abedalkareem/LanguageManager-iOS/issues/12

**Comment by sam961** [comment]
Still not working.... i downloaded also the zip folder inside the issue #12 but also the alignment didn't change in this example

**Comment by Abedalkareem** [comment]
@sam961 
No, don't download anything just read this:
https://github.com/Abedalkareem/LanguageManager-iOS/issues/12#issuecomment-529103380
