### ISSUE TITLE
Error: Did you set the default language for the app?

### ISSUE THREAD

**Issue by Giatrakis** [Abedalkareem/LanguageManager-iOS#49]
When I run the application on my actual device with iOS 12.4.6 the operation is stopped with this error: Did you set the default language for the app?

I have set the default language in AppDelegate inside didFinishLaunchingWithOptions like this:
LanguageManager.shared.defaultLanguage = .deviceLanguage

It works perfectly on the simulator with iOS 13.5.

**Comment by niazi619** [comment]
Please use this code in line number 47. I hope this will resolve your issue.

let currentLang = UserDefaults.standard.string(forKey: Constants.defaultsKeys.selectedLanguage) ?? Locale.current.languageCode
        return Languages(rawValue: currentLang ?? "en")!

**Comment by Giatrakis** [comment]
> Please use this code in line number 47. I hope this will resolve your issue.
> 
> let currentLang = UserDefaults.standard.string(forKey: Constants.defaultsKeys.selectedLanguage) ?? Locale.current.languageCode
> return Languages(rawValue: currentLang ?? "en")!

I tried this but it doesn't work...

public var currentLanguage: Languages {
    get {
        let currentLang = UserDefaults.standard.string(forKey: Constants.defaultsKeys.selectedLanguage) ?? Locale.current.languageCode
        return Languages(rawValue: currentLang ?? "en")!
    }
    set {
      UserDefaults.standard.set(newValue.rawValue, forKey: Constants.defaultsKeys.selectedLanguage)
    }
  }

**Comment by Abedalkareem** [comment]
When you get this error that means that you are using the library before setting the default language.
make sure to add this 
`LanguageManager.shared.defaultLanguage = .deviceLanguage`
in the first line before doing anything.

**Comment by niazi619** [comment]
> When you get this error that means that you are using the library before setting the default language.
> make sure to add this
> `LanguageManager.shared.defaultLanguage = .deviceLanguage`
> in the first line before doing anything.

This is not working bro

**Comment by abdulazizSi** [comment]
The solution may sound crazy but it's worked for me, copy this struct to the first view controller your app is going to open i.e rootViewController

`struct languageSetter {
    
    static func set() -> String {
        
        if #available(iOS 13.0, *) {}
        else {
            LanguageManager.shared.defaultLanguage = .ar
        }
        return ""
    }
}`


and then inside the class of the same viewController just declare this above "viewDidLoad"

`let setter : String = languageSetter.set()`  

Done, Hope it works for you

you can find the explanation of this trick here:

https://medium.com/@lukasthinks/appdelegate-is-not-the-first-code-to-run-54c1535db443

@niazi619 @Giatrakis

**Comment by Abedalkareem** [comment]
@abdulazizSi Thank you for your comment, 
This issue happens when you use the library before setting the default language. So you need to make sure to set the default language before trying to use the library.

Thank you.

**Comment by DrJapan** [comment]
I'm having this issue, but only on an iPad. I'm not sure if it is just this iPad. I have a bunch of other iPhones, and my app works there, but on iPad I get the "did you set the default language" error. Any ideas why they iPad would be different?

Cheers!

**Comment by MMohamad70** [comment]
@DrJapan I have the same problem on iPad, can you share your solution? what is wrong in SceneDelegate?
