### ISSUE TITLE
App crashes after the changing the language a third time.

### ISSUE THREAD

**Issue by amglol** [Abedalkareem/LanguageManager-iOS#51]
I get this error Thread 1: EXC_BAD_ACCESS (code=2, address=0x7ffee374c9d0) for line 187 in LanguageManager.swift

This is the scenario, I load the application change the language to Spanish. I then change the language back to English, no problem. When I go to change the language back again (3rd time) to Spanish the app goes into a infinite loop in the changeViewController() function on line 184

**Comment by Abedalkareem** [comment]
Hi Amglol,

I tried to reproduce this issue multiple times with no luck. Are you still facing this issue? if yes can you please give me more details about this issue?

Thank you.

**Comment by Abedalkareem** [comment]
Closed for not having a response, i will assume it's solved.

Thank you.
