### ISSUE TITLE
SPM 1.2.2 broken - Missing import UIKit

### ISSUE THREAD

**Issue by quentinSquad** [Abedalkareem/LanguageManager-iOS#54]
SPM version impacted : `1.2.2`

How to fix: Add the following line in  https://github.com/Abedalkareem/LanguageManager-iOS/blob/ec9f9afc3f90cdc69a576858d0e7165dbde854e9/LanguageManager-iOS/Classes/Helpers/Extensions/UIView%2BDirection.swift#L9
```
import UIKit
```

**Comment by Abedalkareem** [comment]
Fixed, Thank you for reporting the issue!
