### ISSUE TITLE
Default Language to Arabic

### ISSUE THREAD

**Issue by AbuMandour** [Abedalkareem/LanguageManager-iOS#55]
when I set the default language to Arabic it didn't work in the real device 
iPhone version 14.0.1
am using SceneDelegate
```
    func scene(_ scene: UIScene, willConnectTo session: UISceneSession, options connectionOptions: UIScene.ConnectionOptions) {
        LanguageManager.shared.defaultLanguage = .ar
}
```
any help ?

**Comment by Abedalkareem** [comment]
Hi,

Please set the default language in the ```application(_ application: UIApplication, didFinishLaunchingWithOptions launchOptions: [UIApplication.LaunchOptionsKey: Any]?)```.

**Comment by Abedalkareem** [comment]
Closed for not having a response, I will assume it's solved.

Thank you.
