### ISSUE TITLE
Cannot import pod in Objective-C project

### ISSUE THREAD

**Issue by Lintom** [Abedalkareem/LanguageManager-iOS#58]
Hello. I have problem when try import pod in existing Objective-C project. I used @import LanguageManager_iOS, but class LanguageManager is absent.

![error_import](https://user-images.githubusercontent.com/895950/104399036-9dc29900-559b-11eb-9ea4-8b1217962e5e.png)

![error_import_2](https://user-images.githubusercontent.com/895950/104399054-a3b87a00-559b-11eb-93a3-a06d383d9cdd.png)

**Comment by Abedalkareem** [comment]
Hi @Lintom,
There is no support for Objective-C for now and I don't think it will be added.
