### ISSUE TITLE
Does it support for Research kit framework?

### ISSUE THREAD

**Issue by devlove1C** [Abedalkareem/LanguageManager-iOS#60]
Hi @dimohamdy @imGokul @Abedalkareem @StevenMagdy 
Can anyone guide me?  how can I use this library for the Research kit framework?
I want to implement RTL and LTR for the Research kit framework in my project.
Research kit link: http://researchkit.org/

Thanks

**Comment by Abedalkareem** [comment]
The creator of this library should support RTL languages. I don't think there is anything to do.
