### ISSUE TITLE
System buttons (cancel, back,...) localization 

### ISSUE THREAD

**Issue by annasfa992** [Abedalkareem/LanguageManager-iOS#62]
i noticed that the system buttons don't get translated to the user's preference localization. it is using the previous language that the user has in.

This is happening in
navigation items -> back, cancel
keyboard buttons -> search, Go
Social share popup -> share, cancel

e.t.c.

Could something be done for these issues?

https://user-images.githubusercontent.com/58655238/108633412-c97b4d80-747c-11eb-915e-b22c97e6bc82.mov

**Comment by Abedalkareem** [comment]
@annasfa992 
You can do something like this:
```
navigationItem.backBarButtonItem = UIBarButtonItem(title: "Back".localiz(), style: .plain, target: nil, action: nil)
```
