### ISSUE TITLE
Text is not localizing by using .localiz() --- ( URGENT )

### ISSUE THREAD

**Issue by TaskeeniOS** [Abedalkareem/LanguageManager-iOS#68]
I added LanguageManager-iOS swift  package to my project for localizing English & arabic. 
For me all the UIelements are transforming rightLeft and Left right while  using .setLanguage to .ar and .en.
But the text is not localizing while calling .localiz() method. 
The breakpoint is hitting inside .localiz() method and no changes occurs for the text. 
Could you please help me to find out. What cause this issue ?

Swift Package Version : LanguageManager-iOS 1.2.6
Xcode version 13.3

**Comment by Abedalkareem** [comment]
Sorry for the late reply.
Most probably the issue is with how the project is configured, can you read the read me file and make sure to do the same steps.

Thanks,

**Comment by EvgeniyMac** [comment]
[Abedalkareem] 
Hi, you can write to change language without reload app use localiz in viewWillAppear.
  override func viewWillAppear(_ animated: Bool) {
        settingLabel.text = "Settings".localiz()
    }
