### ISSUE TITLE
SPM not working on Xcode 13.4

### ISSUE THREAD

**Issue by CavalcanteLeo** [Abedalkareem/LanguageManager-iOS#69]
As you can see in the prints:

dependency rules: `up to next major version`
<img width="1127" alt="Screen Shot 2022-05-24 at 14 34 26" src="https://user-images.githubusercontent.com/1735944/170097559-ee318654-0132-4175-a7e3-0fac4f3ed4fe.png">

dependency rules: `branch`
<img width="1100" alt="Screen Shot 2022-05-24 at 14 33 53" src="https://user-images.githubusercontent.com/1735944/170097576-ce2d242e-03f2-4abd-839b-535c86ff9f2d.png">

**Comment by Abedalkareem** [comment]
Fixed with 1.2.7.
Thanks!
