### ISSUE TITLE
[!] Unable to find a specification for `LanguageManger-iOS`

### ISSUE THREAD

**Issue by AnasAlsaadi** [Abedalkareem/LanguageManager-iOS#7]

**Comment by Md-Rais** [comment]
Hi, I am getting the same issue
[!] Unable to find a specification for `LanguageManger_iOS` at terminal
Any solution for this?

**Comment by Md-Rais** [comment]
????

**Comment by Abedalkareem** [comment]
Hi,

Please be sure to use "-" instead of "_".

pod 'LanguageManger-iOS'

**Comment by Md-Rais** [comment]
Hi Abedalkareem,
I have used "-" as well and still I am getting the following error after entering the command pod install at the terminal.

[!] Unable to find a specification for `LanguageManger-iOS`

Please check it, as I am not able to install it into my project. Or let me know the steps if I can install it just using the folder manually.

Waiting!

**Comment by Abedalkareem** [comment]
Hello,

You can take this class `LanguageManger.swift` and add it to your project directly.

https://github.com/Abedalkareem/LanguageManger-iOS/tree/master/LanguageManger-iOS/Classes

Thank you, and i'm sorry for the delay.

**Comment by Abedalkareem** [comment]
Hi !

I just pushed new version, you can try now.

  `pod 'LanguageManager-iOS'`

Thank you !!!
