### ISSUE TITLE
Add PrivacyInfo.xcprivacy because of UserDefaults usage

### ISSUE THREAD

**Issue by ksa-real** [Abedalkareem/LanguageManager-iOS#73]
Apple requires the mentioned files if some APIs are used.
I see a usage here:
https://github.com/Abedalkareem/LanguageManager-iOS/blob/master/LanguageManager-iOS/Classes/Helpers/Storage.swift
More info here:
https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

**Comment by AbuMandour** [comment]
We face the same issue :(

**Comment by AbuMandour** [comment]
> Apple requires the mentioned files if some APIs are used. I see a usage here: https://github.com/Abedalkareem/LanguageManager-iOS/blob/master/LanguageManager-iOS/Classes/Helpers/Storage.swift More info here: https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api

I found the solution just add privacy file to your app with UserDefault it will apply to all the libraries you are using

**Comment by Abedalkareem** [comment]
Hi,
Released with 1.3.0,
Can you please check?

Sorry for the delay.
