### ISSUE TITLE
ITMS-91108: Invalid privacy manifest

### ISSUE THREAD

**Issue by AhmedSOULEIMANI** [Abedalkareem/LanguageManager-iOS#75]
Hello,

I started to have this error from Apple :
ITMS-91108: Invalid privacy manifest - The PrivacyInfo.xcprivacy file from the following path is invalid: “Frameworks/LanguageManager_iOS.framework/LanguageManager-iOS.bundle/PrivacyInfo.xcprivacy”. In addition to the privacy manifest files in the locations outlined in the documentation

I believe it might be related to the key "NSPrivacyAccessedAPIType" underneath the key of "NSPrivacyAccessedAPITypes" as I could not find anything related the "NSPrivacyAccessedAPIType".
Apple is giving this documentation website to review : https://developer.apple.com/documentation/bundleresources/privacy_manifest_files
And if we check more closely, we couldn't find anything related to "NSPrivacyAccessedAPITypeReasons" given value inside the [NSPrivacyAccessedAPITypes](https://developer.apple.com/documentation/bundleresources/privacy_manifest_files/describing_use_of_required_reason_api)
It needs to be one of these : "CA92.1" , "1C8F.1", "C56D.1", "AC6B.1"

Can you please check this ?

**Comment by mitulsavani** [comment]
Our team is also facing the exact same error. Please provide updates at your earliest convenience.

**Comment by AnugrahChaturvedi74** [comment]
getting the same issue please update any one got any solution

**Comment by Abedalkareem** [comment]
Hi, 
Thanks for reporting I'll do it today.

**Comment by AhmedSOULEIMANI** [comment]
I made [this pull request](https://github.com/Abedalkareem/LanguageManager-iOS/pull/76) fixing the issue

**Comment by prakashfs** [comment]
When are we going to get latest version post this fix merge?

**Comment by mitulsavani** [comment]
When @Abedalkareem do you plan to release #76 ? Our org uses this dependency on a prod application.

**Comment by Abedalkareem** [comment]
Hi,
Released with 1.3.0,
Can you please check?

Sorry for the delay.

**Comment by mataman737** [comment]
Hi, yes. Updated to 1.3.0 and it appears to work. Was able to archive and upload a new build to App Store for review.

**Comment by AhmedSOULEIMANI** [comment]
Issue has been Indeed solved through version 1.3.0
Closing the issue as solved 👍
